language: node_js

node_js:
- '12.4.0'

os:
- linux

group: dev
sudo: required
dist: xenial

branches:
  only:
  - master

install:
- npm install

script:
- node ./node_modules/osm-tile-downloader/osm-tile-downloader.js --start-zoom-level 2 --end-zoom-level 6 --url https://b.tile.openstreetmap.org/{z}/{x}/{y}.png --output-dir ./tiles/ --delay 10 --yes
- zip -r /tmp/flight-planner.zip ./src/ ./tiles/ flight.html LICENSE
- mv /tmp/flight-planner.zip ./flight-planner.zip

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.zip"
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME == linux"
